name: Deploy container

on:
    workflow_run:
        workflows: [Test and push container]
        types:
        - completed
    workflow_dispatch:
      
jobs:

  deploy-on-server:
    runs-on: self-hosted

    container: 
      image: node:26-alpine
      volumes:
        - "/var/www/html:/host"

    steps:
      - name: build
        uses: actions/checkout@v4

      - name: Execute docker compose
        run: |
          echo "\
          export const environment = {\
              production: ${{secrets.PRODUCTION}},\
              apiAddr: '${{secrets.APIADDR}}'\
          };" > ./src/environments/environment.development.ts

          npm install
          npm run build
            
      - name: Deploy to Nginx
        run: cp -r -f dist/PATO-web-client/browser/* /host/